---
- name: Monitor and Start HTTPD if Disabled
  hosts: [Test]  # Replace with your target hosts or group
  become: yes

  tasks:
    - name: Check HTTPD status
      command: systemctl status httpd
      register: httpd_status
      ignore_errors: yes

    - name: Start HTTPD if disabled
      when: httpd_status.rc != false
      become: yes
      become_user: root
      command: systemctl start httpd
